### ISSUE TITLE
Please the bot wont launch up

### ISSUE THREAD

**Issue by Aricingfc** [silvanohirtie/account-generator#18]
Error: Cannot find module 'C:\Users\sktmo\source\repos\install'
Please it wont work i typed - 
node index.js
then it brings me up with that

**Comment by JavaScriptOP** [comment]
> Error: Cannot find module 'C:\Users\sktmo\source\repos\install'
> Please it wont work i typed -
> node index.js
> then it brings me up with that

learn javascript, and look at the first line. folders are not supposed to have `'` in it. go in the bot folder, type npm install, after that is done, type `node .`

**Comment by bernawastaken** [comment]
@Aricingfc First open the folder you have the bot on in a command prompt, then type `npm install` (make sure you have both node.js and npm installed on your computer) 
![image](https://user-images.githubusercontent.com/43864475/99791119-0f8ee100-2b1d-11eb-9b50-ff0fd1582dd7.png)
Then you can write `node index.js` and given that you follow what I said in your issue #19 it should be good to go 
![image](https://user-images.githubusercontent.com/43864475/99791580-b7a4aa00-2b1d-11eb-9859-c55e9dce873e.png)

Now just like I said in Issue #19 you should read some of the JavaScript or Node.js basics in order to feel more comfortable using this system but it's up to you 👍

**Comment by silvanohirtie** [comment]
@bernawastaken gave an awesome reply, closing issue
